version: "3"
# Could switch back to Version 2 if something breaks. Also, not specifying minor version here which might be best practice.
services:
  # Jaeger
  # jaeger-all-in-one:
  #   image: jaegertracing/all-in-one:latest
  #   restart: always
  #   ports:
  #     - "16686:16686"
  #     - "14268"
  #     - "14250"

  # Zipkin
  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   restart: always
  #   ports:
  #     - "9411:9411"

  # Collector
  otel-collector:
    # image: ${OTELCOL_IMG}
    # image: otel/opentelemetry-collector:0.67.0
    # image sourced from OTel docs (collector/getting-started)
    image: otel/opentelemetry-collector-contrib:0.76.1
    container_name: otel-col
    restart: always
    volumes:
      - ./collector-gateway-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    # depends_on:
      #- jaeger-all-in-one
      # - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"